### PR TITLE
✨ Added Gamma Function

### PR DESCRIPTION
**Pull request by h3athen**

### CODE REVIEW

**Comment by ChrisO345** [comment]
The whole point of having a seperate file for the gamma function is to account for complex numbers

**Comment by h3athen** [comment]
There was two gamma file. One outside the complex which I have PR for. And the other gamme file was inside the complex folder which I think is for complex numbers.

**Comment by ChrisO345** [comment]
that's my bad. there was only supposed to be one file

**Comment by h3athen** [comment]
Alrighty ill start working on the complex numbers

**Comment by ChrisO345** [comment]
Awesome thank you!

**Pull request closed without merging**
