### PR TITLE
Added Gamma Function

### PR DESCRIPTION
**Pull request by h3athen**

### CODE REVIEW

**Comment by ChrisO345** [comment]
This works for positive values, however not for negative values.

**Comment by h3athen** [comment]
Okay will work on negative values

**Comment by h3athen** [comment]
Hey can you check if this works

**Comment by ChrisO345** [comment]
This seems to work on the most part, however there are some values that do not work, ie -4.5

**Comment by h3athen** [comment]
alright working on it

**Comment by h3athen** [comment]
Can you pls check

**Pull request closed without merging**
